// demo/svelte/ResponsiveTable.svelte
<!--
  ResponsiveTable — A Svelte component that makes HTML tables responsive.

  On mobile viewports, each <td> gets a label injected from its column header,
  allowing the table to stack vertically while remaining readable.

  Uses the same CSS approach as the jQuery version (responsive-table.css).

  Props:
    headers  — Array of column header strings, e.g. ["Name", "Age", "Email"]
    rows     — Array of arrays, each inner array is one row of cell values
    className — Optional additional class name (default: "content-table")
-->
<script>
  export let headers;
  export let rows;
  export let className = "content-table";
</script>

<table class={className}>
  <thead>
    <tr>
      {#each headers as header, i}
        <th>{header}</th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each rows as row, rowIndex}
      <tr>
        {#each row as cell, colIndex}
          <td>
            <span class="mobile-th">{headers[colIndex]}</span>
            {cell}
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

// demo/react/ResponsiveTable.jsx
/**
 * ResponsiveTable — A React component that makes HTML tables responsive.
 *
 * On mobile viewports, each <td> gets a label injected from its column header,
 * allowing the table to stack vertically while remaining readable.
 *
 * Uses the same CSS approach as the jQuery version (responsive-table.css).
 *
 * Props:
 *   headers  — Array of column header strings, e.g. ["Name", "Age", "Email"]
 *   rows     — Array of arrays, each inner array is one row of cell values
 *   className — Optional additional class name (default: "content-table")
 */
function ResponsiveTable({ headers, rows, className = "content-table" }) {
  return (
    <table className={className}>
      <thead>
        <tr>
          {headers.map((header, i) => (
            <th key={i}>{header}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, rowIndex) => (
          <tr key={rowIndex}>
            {row.map((cell, colIndex) => (
              <td key={colIndex}>
                <span className="mobile-th">{headers[colIndex]}</span>
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
